name: CI

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Docker Compose
        run: docker-compose up -d

      - name: Delay for 5 seconds
        run: sleep 5
            
      - name: Run CRUD Tests
        run: |
              cd Part_A && npm ci && npm test
      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: Newman_Report
          path: Part_A/reports/report.html
      - name: Tear Down Docker Containers
        run: docker-compose down -v
